### PR TITLE
feat: Added Dockerfile and optimized Collector and generate_reference

### PR DESCRIPTION
**Pull request by dploeger**
**Please check if the PR fulfills these requirements:**

- [x] The commit message follows our guidelines.
- For bug fixes and features:
    - [x] You tested the changes.
    - [x] You updated the docs or changelog.

**What kind of change does this PR introduce?**

Apart from some optimizations in the collector and making generate_reference shellcheck-stable, a Dockerfile was added to generate a Container image for the gdscript-docs-maker.

I'd suggest deploying this image to Docker Hub so that it's easy to run this locally or even in Github Actions or the like.

I can support in creating the pipeline to deploy it to the hub.

**Does this PR introduce a breaking change?**

no

### CODE REVIEW

**Comment by dploeger** [comment]
@NathanLovato No need to hurry this up, but I'd like to know if you'd be interested in releasing the docker image that I suggested in this PR. I'd need it for the Escoria rewrite and EgoVenture. If you don't I'll release it myself.

Thanks!

**Comment by NathanLovato** [comment]
Why not. I've rarely used docker and never set up a dockerfile, so could you tell me how this works? You add the file to this repo and people can directly get docs maker set up in a project?

Also I looked at the changes but it's hard to see what changed with the diff, gotta give it a quick test to see everything's still working as expected before merging. I'll add it to my tasklist to do by the end of the weekend.

**Comment by dploeger** [comment]
People can build a local image from the Dockerfile by using `docker build -t gdscripts-doc-maker:local .` and then document their game by mounting in the game and output directories in the container and running generate_reference with this command:

`docker run --rm -v /path/to/my/game:/game -v /path/to/my/docs:/output gdscript-docs-maker:local /game -o /output -d addons/my-addon`

(`--rm` means: Remove container after running, `-v`'s mean: Mount the local directory on the left side of the : into the container path which is the right side of the :, then come the name of the container image and parameters to generate_reference)

So, this works, but it would be even more easy for people if we can publish the image on [Docker hub](https://hub.docker.com) and regulary build images there (e.g. using the respective [Github actions](https://github.com/marketplace/actions/build-and-push-docker-images)), so people can - without downloading the repository - run for example:

`docker run --rm -v /path/to/my/game:/game -v /path/to/my/docs:/output gdscript-docs-maker:1.6.0 /game -o /output -d addons/my-addon`

You just need to [install Docker](https://www.docker.com/get-started), which most developers nowadays already have.

Also, you can use this container for automating generating the API reference when releasing addons to the asset lib like I'm doing with [EgoVenture addons](https://github.com/deep-entertainment/egoventure/blob/master/.github/workflows/assetlib.yml) currently.

**Comment by dploeger** [comment]
Thanks for checking it out!

**Comment by dploeger** [comment]
Oh, should I add the GitHub actions to publish the container image to this pr?

**Comment by NathanLovato** [comment]
Just tested the changes, everything's working fine. Thanks.

> Oh, should I add the GitHub actions to publish the container image to this pr?

I don't know who uses docker or, in this case, why you'd want it over a simple build script. But if that's useful to some people, starting with you, and you maintain it if need be, why not.

Just let me know when it's ready to merge

**Comment by dploeger** [comment]
It would be very valuable to automatic API generation for EgoVenture and Escoria. For this to work, we'd need to sign up to docker hub and define an image name.

If you don't want to sign up, I could create an organization (e.g. gdquest) there so it's not bound to my account. As an image name I'd suggest the obvious <new organization-name>/gdscript-docs-maker.

And sure, I can maintain the image (although it will be updated with every new version anyways. :) )

**Comment by NathanLovato** [comment]
If you don't mind taking care of putting the image on docker hub that'd be welcome.

Please excuse the reply delays, we're especially busy wrapping up our new product.

**Comment by dploeger** [comment]
Added the github workflow. I hope that after merging, it will automatically build a "latest" image based on the default branch. If you then release a new version (starting with "v") it will release that version to docker as well. (and every push to the default branch and every release)

Thanks for the support! ❤️

**Comment by NathanLovato** [comment]
Thanks much for the contribution!

**Comment by dploeger** [comment]
Yes! And it worked: https://hub.docker.com/layers/gdquest/gdscript-docs-maker/master/images/sha256-91128b5e47425d76a4de5fc13bd9732822ff41027039ad9e7030bab9a65ce679?context=explore


Thanks a lot!

**Pull request merged**
