### PR TITLE
feat: Better recognition of the Godot command and support of Godot 4

### PR DESCRIPTION
**Pull request by AdrasteonDev**
**Please check if the PR fulfills these requirements:**

- [X] The commit message follows our guidelines.
- For bug fixes and features:
    - [X] You tested the changes.

Related issue (if applicable): No related issues

**What kind of change does this PR introduce?**

This PR introduces these changes related to the bash/batch files:

- Support for Godot 3.5 and 4
- Better recognition of Godot within PATH
- Better macOS support in the generate_reference file
  - Better interpretation of arguments (I replaced getopt by getopts, which also works on macOS)
  - Fix sed command call for macOS
- README update

Tested with Godot 3 and 4 on Windows, macOS and Linux

**Does this PR introduce a breaking change?**

The double dash arguments ("--format", "--directory", ...) are no longer supported by the generate_reference script (because of the use of getopts)

## New feature or change ##

**What is the current behavior?** 

- Godot 4 is not supported
- Godot 3.5 is not supported on Windows (there is a bug with the "_console.cmd" executable of Godot)
- Godot is found in PATH on Linux and macOS only if a command named "godot" exists
- Bugs prevent generate_reference from working correctly on macOS (related to getopt and sed calls)

**What is the new behavior?**

- Godot 4 is supported (`##` comments are recognized as docstrings)
- Godot 3.5 is supported
- Godot is found in PATH on Linux and macOS:
  - The Godot app file is found on macOS
  - The Godot executable is found on macOS and Linux if zsh or bash is installed on the system (and if the executable name have not been changed since the download of Godot from the Godot website)
- No more bugs preventing generate_reference to work correctly on macOS (the sed call is fixed and getopts replaces getopt)

**Other information**

I have not yet modified the CHANGELOG file

Let me know if you think I have any other changes to make

### CODE REVIEW

**Comment by NathanLovato** [comment]
Thank you so much for taking the time to update the project! I'm on the tablet right now and could only review the code briefly but the changes look great at a glance. I'm taking note to test this and review more carefully by the end of the week.

If I understand correctly, `getopts` does not allow for long form command-line options, but it's more portable, is this correct? I like the long options for writing clearer commands, for example, in a continuous integration, but I guess this would be a fine trade-off to make if there is no alternative.

If there was an alternative such as rewriting the command arguments, e.g. `sed s/--format/-f` before running through `getopts`, just to preserve long option support, that'd be ideal. Though if not, it's OK too.

**Comment by AdrasteonDev** [comment]
Here is what I found about getopt and getopts:

- [According to this answer](https://stackoverflow.com/questions/11777695/why-the-getopt-doesnt-work-well-in-my-mac-os), getopt is BSD-based on macOS, and gnu-based on Linux
- [According to Wikipedia](https://en.wikipedia.org/wiki/Getopt#In_Shell), getopts is a part of the POSIX Shell standard, and is more portable

I will check if I can find a way to support long form command-line options.

And by the way, thanks for sharing my pull request on social networks :)

**Comment by AdrasteonDev** [comment]
Getopts seems to be designed primarly for short options, But I found [this answer](https://stackoverflow.com/a/28466267)

I tested it on Linux and it works. But you have to use one of these syntax:
- `--format=hugo`
- `--format='hugo'`
- `--format="hugo"`

The syntax `--format "hugo"` (with a space) doesn't work.

If you agree with this solution, I will push a new commit tomorrow.

**Comment by NathanLovato** [comment]
That sounds great to me! With an error message saying something like 

"Option $OPT needs an argument, but it was not found. Note that arguments must be provided like this: --option=argument, with an equal sign. Spaces between options and their argument are not supported."

To make usage extra clear, as it's not the most common behavior on the command line.

**Comment by AdrasteonDev** [comment]
Well, after a few hours, I finally found a way to support both syntaxes for long options (`--format hugo` and `--format=hugo`). I tested it quickly on Linux and it seems to work.

The solution is based on OPTIND (a variable used by getopts).

I will try to push a new commit tomorrow.

**Comment by NathanLovato** [comment]
Thanks, that sounds amazing!

**Comment by AdrasteonDev** [comment]
It is done !

**Comment by NathanLovato** [comment]
Great job! Thanks much for the work.

**Pull request merged**
